# Generated by Django 3.1.2 on 2020-11-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='precio_producto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
