# Generated by Django 3.1.2 on 2020-11-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_inventario_precio_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='precio_unidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad_producto',
            field=models.IntegerField(default=1),
        ),
    ]
