# Generated by Django 3.1.2 on 2020-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_auto_20201125_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente_id',
            field=models.IntegerField(),
        ),
    ]
