# Generated by Django 3.1.2 on 2020-11-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_auto_20201130_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.cliente'),
        ),
    ]
