# Generated by Django 3.1.2 on 2020-12-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_auto_20201130_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='activado/desactivado'),
        ),
    ]
